[package]
name = "day_07"
version = "0.1.0"
authors = ["Bart Slinger <bartslinger@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
aoc = { path = "../aoc" }
itertools = "0.8.2"